# name: Train-in-the-cloud
# on: [push]
# jobs:
#   deploy-runner:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: iterative/setup-cml@v1
#       - uses: actions/checkout@v3
#       - name: Deploy runner on EC2
#         env:
#           GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
#         run: |
#           cml runner launch \
#             --cloud=gcp \
#             --cloud-region=europe-west4-b \
#             --cloud-type=g4dn.xlarge \
#             --labels=cml-gpu
#   train-model:
#     needs: deploy-runner
#     runs-on: [self-hosted, cml-gpu]
#     timeout-minutes: 50400 # 35 days
#     container:
#       image: ghcr.io/iterative/cml:0-dvc2-base1-gpu
#       options: --gpus all
#     steps:
#       - uses: actions/checkout@v3
#       - name: Train model
#         env:
#           REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
#         run: |
#           pip install -r requirements.txt
#           python main.py

#           cat metrics.txt > report.md
#           cml comment create report.md

name: model-training
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          # Install requirements
          pip install -r requirements.txt

          # Pull data & run-cache from S3 and reproduce pipeline
          # dvc pull data --run-cache
          # dvc repro
          
          python main.py

          # Report metrics
          echo "## Metrics" >> report.md
          git fetch --prune
          dvc metrics diff master --show-md >> report.md

          # Publish confusion matrix diff
          echo "## Plots" >> report.md
          echo "### Class confusions" >> report.md
          dvc plots diff --target classes.csv --template confusion -x actual -y predicted --show-vega master > vega.json
          vl2png vega.json -s 1.5 > confusion_plot.png
          echo "![](./confusion_plot.png)" >> report.md

          # Publish regularization function diff
          echo "### Effects of regularization" >> report.md
          dvc plots diff --target estimators.csv -x Regularization --show-vega master > vega.json
          vl2png vega.json -s 1.5 > plot.png
          echo "![](./plot.png)" >> report.md

          cml comment create report.md