name: Train-in-the-cloud
on: [push]
jobs:
  deploy-runner:
    runs-on: ubuntu-latest
    permissions:
        contents: 'read'
        id-token: 'write'
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
      - name: Deploy runner on EC2
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        
        run: |
          cml runner launch \
            --cloud=gcp \
            --cloud-region=europe-west4-b \
            --cloud-type=g4dn.xlarge \
            --labels=cml-gpu
  train-model:
    needs: deploy-runner
    runs-on: [self-hosted, cml-gpu]
    timeout-minutes: 50400 # 35 days
    container:
      image: ghcr.io/iterative/cml:0-dvc2-base1-gpu
      options: --gpus all
      
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/1037547109290/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
          service_account: 'my-service-account@dtumlops-374307.iam.gserviceaccount.com'
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc pull
          python main.py

          # cat metrics.txt > report.md
          # cml comment create report.md

#  permissions:
#       contents: 'read'
#       id-token: 'write'
#     steps:
#       - uses: actions/checkout@v3
#       - id: 'auth'
#         name: 'Authenticate to Google Cloud'
#         uses: 'google-github-actions/auth@v1'
#         with:
#           workload_identity_provider: 'projects/1037547109290/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
#           service_account: 'my-service-account@dtumlops-374307.iam.gserviceaccount.com'

# name: model-training
# on: [push]
# jobs:
#   run:
#     runs-on: ubuntu-latest
#     container: ghcr.io/iterative/cml:0-dvc2-base1
#     steps:
#       - uses: actions/checkout@v3
#       - name: Train model
#         env:
#           GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
#         run: |
#           git config --global --add safe.directory /__w/DTU_MLops_M21_docker_example/DTU_MLops_M21_docker_example
#           # Install requirements
#           pip install -r requirements.txt

#           # Pull data & run-cache from S3 and reproduce pipeline
#           # dvc pull data --run-cache
#           # dvc repro

#           python main.py